fixtures:
  symlinks:
    "tsm": "#{source_dir}"
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.11.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "2.1.0"
